laravelprueba:
  build : .
  dockerfile: Dockerfile
  links:
    - mydb:mysql
  volumes:
    - ./:/var/www/html/
  ports:
    - 8080:80

mydb:
  image: mysql:5.7
  ports : 
    - 3333:3306
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  